start "" /b "c:\Program Files\Derivative\TouchDesigner.2023.11760\bin\TouchDesigner.exe" MidLEDKinect_11760.toe
TIMEOUT /T 5 /NOBREAK
start "" /b "c:\Program Files\Derivative\TouchDesigner\bin\TouchDesigner.exe" MidLED_RENDER_30770.toe
start "" /b "c:\Program Files\Derivative\TouchDesigner\bin\TouchDesigner.exe" MidLED_OUTPUT_30770.toe
REM start "" /b "c:\Program Files\Derivative\TouchDesigner.2025.31550\bin\TouchDesigner.exe" MidBurn_LucidLED_RENDER_31550.toe